const directoryData = [
    {
        "name": "Martin Superville",
        "category": "Artists",
        "type": "Artist / Painter",
        "region": "Southwest",
        "area": "Lowlands",
        "photo": "martin_superville.jpg",
        "description": "Renowned Tobago artist known for vibrant depictions of island life and culture.",
        "id": "loc-1",
        "dot": [2800, 2800],
        "box": [1300, 3200, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Dean Martin",
        "category": "Artists",
        "type": "Artist",
        "region": "Scarborough/Central",
        "area": "Scarborough",
        "photo": "dean_martin.jpg",
        "description": "Local artist capturing the essence of Tobago through expressive works.",
        "id": "loc-2",
        "dot": [2850, 2850],
        "box": [1700, 3200, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Ikechukwu Ojuro",
        "category": "Artists",
        "type": "Designer / Artist",
        "region": "Scarborough/Central",
        "area": "Scarborough",
        "photo": "ike_ojuro.jpg",
        "description": "Contemporary designer and artist pushing creative boundaries in Tobago.",
        "id": "loc-3",
        "dot": [2900, 2900],
        "box": [2100, 3200, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Shaw Park Cultural Complex",
        "category": "Cultural Sites",
        "type": "Arts Venue / Cultural Space",
        "region": "Scarborough/Central",
        "area": "Shaw Park",
        "photo": "shaw_park.jpg",
        "address": "Shaw Park, Scarborough, Tobago",
        "description": "Tobago's premier performing arts theater and exhibition space.",
        "id": "loc-4",
        "dot": [3000, 2950],
        "box": [2500, 3200, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Culture"
    },
    {
        "name": "Tobago Museum",
        "category": "Museums",
        "type": "Museum",
        "region": "Scarborough/Central",
        "area": "Scarborough",
        "photo": "tobago_museum.jpeg",
        "address": "84 Fort Street, Scarborough, Tobago (Inside Fort King George)",
        "description": "Located within Fort King George, showcasing the rich history of Tobago.",
        "id": "loc-5",
        "dot": [3100, 3000],
        "box": [2900, 3200, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Gallery"
    },
    {
        "name": "Magdalena Art Gallery",
        "category": "Galleries",
        "type": "Art Gallery",
        "region": "Southwest",
        "area": "Lowlands",
        "photo": "magdalena_gallery.jpg",
        "description": "A premium space showcasing local and regional fine art.",
        "id": "loc-6",
        "dot": [3200, 3050],
        "box": [3300, 3200, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Gallery"
    },
    {
        "name": "Shonari Richardson",
        "category": "Artists",
        "type": "Artist",
        "region": "Scarborough/Central",
        "area": "Scarborough",
        "photo": "shonari_richardson.png",
        "description": "Contemporary Tobago artist focusing on cultural themes.",
        "id": "loc-7",
        "dot": [3300, 3100],
        "box": [3700, 3200, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Nick McKenna",
        "category": "Artists",
        "type": "Artist",
        "region": "Scarborough/Central",
        "area": "Scarborough",
        "photo": "nick_mckenna.png",
        "description": "Artist known for unique perspectives on Tobago's landscape.",
        "id": "loc-8",
        "dot": [3400, 3150],
        "box": [4100, 3200, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Anthony Mckenna",
        "category": "Artists",
        "type": "Artist",
        "region": "Southwest",
        "area": "Crown Point",
        "photo": "anthony_mckenna.jpg",
        "description": "Creative spirit based in the vibrant Crown Point area.",
        "id": "loc-9",
        "dot": [1700, 3200],
        "box": [50, 2000, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Gary's Wraps",
        "category": "Creative Businesses",
        "type": "Creative Business",
        "region": "Southwest",
        "area": "Crown Point",
        "photo": "garys_wraps.jpg",
        "description": "Innovative local brand blending creativity with commerce.",
        "id": "loc-10",
        "dot": [1750, 3150],
        "box": [450, 1600, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Planet Ceramics",
        "category": "Workshops",
        "type": "Ceramic Studio",
        "region": "Southwest",
        "area": "Southwest Tobago",
        "photo": "planet_ceramics.jpeg",
        "description": "Ceramic studio and workshop producing unique island-inspired pottery.",
        "id": "loc-11",
        "dot": [1800, 3100],
        "box": [50, 1600, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Renee Benjamin",
        "category": "Artists",
        "type": "Artist",
        "region": "Southwest",
        "area": "Crown Point",
        "photo": "renee_benjamin.jpg",
        "description": "Artist capturing the light and life of Southwest Tobago.",
        "id": "loc-12",
        "dot": [1650, 3250],
        "box": [450, 2000, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Joseph Bacchus",
        "category": "Artists",
        "type": "Artist",
        "region": "Southwest",
        "area": "Crown Point",
        "photo": "joseph_bacchus.jpg",
        "description": "Local artist with a deep connection to the Crown Point community.",
        "id": "loc-13",
        "dot": [1600, 3300],
        "box": [850, 2000, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Collis Street Art",
        "category": "Public Art",
        "type": "Street Artist",
        "region": "Southwest",
        "area": "Crown Point",
        "photo": "collis_street_art.jpg",
        "description": "Vibrant street art that brings the walls of Crown Point to life.",
        "id": "loc-14",
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Amber Shaw",
        "category": "Artists",
        "type": "Artist",
        "region": "Western Coast",
        "area": "Plymouth",
        "photo": "amber_shaw.jpeg",
        "description": "Plymouth-based artist known for intricate and meaningful works.",
        "id": "loc-15",
        "dot": [2450, 1950],
        "box": [50, 400, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Kimme Museum",
        "category": "Museums",
        "type": "Museum / Sculpture Garden",
        "region": "Western Coast",
        "area": "Mt. Irvine / Bethel",
        "photo": "kimme_museum.jpg",
        "address": "Kimme Drive, Bethel, Tobago",
        "description": "The castle-like studio and museum of the late Luise Kimme, featuring monumental sculptures.",
        "id": "loc-16",
        "dot": [2350, 2300],
        "box": [450, 400, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Gallery"
    },
    {
        "name": "Arletys Arias",
        "category": "Artists",
        "type": "Artist",
        "region": "Western Coast",
        "area": "Plymouth",
        "photo": "arletys_arias.jpg",
        "description": "Artist bringing a unique contemporary voice to the Plymouth region.",
        "id": "loc-17",
        "dot": [2420, 1980],
        "box": [850, 400, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Chinyere Herbert",
        "category": "Artists",
        "type": "Graphic Designer / Curator",
        "region": "Western Coast",
        "area": "Plymouth",
        "photo": "chinyere_herbert.jpeg",
        "description": "Multi-disciplinary creative, graphic designer and art curator.",
        "id": "loc-18",
        "dot": [2480, 2020],
        "box": [1250, 400, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Tomley Roberts",
        "category": "Artists",
        "type": "Artist",
        "region": "Western Coast",
        "area": "Plymouth",
        "photo": "tomley_roberts.jpg",
        "description": "Artist and educator deeply rooted in Tobago's art education and creation.",
        "id": "loc-19",
        "dot": [2520, 2050],
        "box": [1650, 400, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Creator"
    },
    {
        "name": "Museum Buccoo",
        "category": "Museums",
        "type": "Museum / Heritage",
        "region": "Western Coast",
        "area": "Buccoo",
        "address": "Buccoo Main Road, Buccoo, Tobago",
        "description": "Community museum celebrating the heritage and culture of Buccoo.",
        "id": "loc-20",
        "dot": [2150, 2650],
        "box": [50, 1200, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Gallery"
    },
    {
        "name": "Healing with Horses",
        "category": "Heritage",
        "type": "Cultural / Experiential Venue",
        "region": "Western Coast",
        "area": "Buccoo",
        "photo": "healing_with_horses.jpg",
        "description": "A therapeutic and cultural center offering unique experiences with horses.",
        "id": "loc-21",
        "dot": [2100, 2700],
        "box": [450, 1200, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Castle"
    },
    {
        "name": "Mystery Tombstone",
        "category": "Heritage",
        "type": "Historical Site",
        "region": "Western Coast",
        "area": "Plymouth",
        "photo": "mystery_tombstone.jpg",
        "description": "A famous historical landmark with an enigmatic inscription from 1783.",
        "id": "loc-22",
        "dot": [2580, 2100],
        "box": [50, 800, 150, 200],
        "contact": "Contact via gallery/venue",
        "iconType": "Castle"
    },
    {
        "name": "Duniesky Lora",
        "category": "Artists",
        "type": "Artist / Sculptor",
        "region": "Western Coast",
        "area": "Plymouth",
        "photo": "duniesky_lora.jpg",
        "description": "Sculptor and artist creating powerful works in the Western Coast region.",
        "id": "loc-23",
        "dot": [2620, 2150],
        "box":
